version: '3'
services:

  pwndoc-frontend-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    
    container_name: pwndoc-frontend-dev
    volumes:
      - ./quasar.conf.dev.js:/app/quasar.conf.js
    restart: always
    ports:
      - 9000:9000
    networks:
      - backend

networks:
  backend:
    external:
      name: backend_backend
